version: "3"

services:
  mongodb:
    build: 
      dockerfile: Dockerfile
      context: ./mongo
    restart: always
    networks:
      - servicesnet
  nodejs:
    depends_on: 
      - mongodb
    build:
      dockerfile: Dockerfile
      context: ./
    restart: always
    networks:
      - servicesnet
    ports:
      - 3333:3333
    environment:
      DATABASE_NAME: services
      DATABASE_USER: admin
      DATABASE_PASSWORD: 1234
      DATABASE_HOST: mongodb
      DATABASE_PORT: 27017

networks:
  servicesnet: